name: Test API in PythonAnywhere

on:
  push:
    branches:
      - main  # o la rama de tu app móvil
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Test /api/login
      run: |
        curl -X POST https://hugoc.pythonanywhere.com/api/login \
        -H "Content-Type: application/json" \
        -d '{"username":"PRUEBA123", "password":"Contrasena123"}' \
        --fail

    - name: Test /api/usertype
      run: |
        curl -X POST https://hugoc.pythonanywhere.com/api/usertype \
        -H "Content-Type: application/json" \
        -d '{"user":"PRUEBA123"}' \
        --fail

    - name: Test /api/verifyEmail
      run: |
        curl -X POST https://hugoc.pythonanywhere.com/api/verifyEmail \
        -H "Content-Type: application/json" \
        -d '{"email":"test@example.com"}' \
        --fail
